{{- if and (not .Values.auth.existingSecret) .Values.auth.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "locus-agent.authSecretName" . }}
  labels:
    {{- include "locus-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.secretKey }}: {{ .Values.auth.apiKey | quote }}
{{- end }}
